dist: xenial
language: haxe

haxe:
  - development
  - stable

jdk:
  - openjdk11

addons:
  apt:
    packages:
      - mono-devel

install:
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs
  - haxelib git hxcs https://github.com/HaxeFoundation/hxcs
  - if [ "${TRAVIS_HAXE_VERSION}" = "3.4.7" ]; then
      haxelib install hxjava;
    else
      haxelib git hxjava https://github.com/HaxeFoundation/hxjava;
    fi

script:
  - echo "haxe=${TRAVIS_HAXE_VERSION}, neko=${TRAVIS_NEKO_VERSION}"
  - make test

